### ISSUE TITLE
 'EXPORT_APPLICATION_TO_CLOB' ORA-06550: line 2, column 5

### ISSUE THREAD

**Issue by ghost** [OraOpenSource/apexbackup#9]
Hi Martin,

I have a second virtual server with a diff db on which I am trying to apply your apex backup solution, but it is giving me the following error:

[oracle@OL7-FilmDemo-11204 apexbackup]$ ./apex_backup.sh 
Loading custom properties

Exporting Application 300:'3rd Forensic - FILM' 
Exception in thread "main" java.sql.SQLException: ORA-06550: line 2, column 11:
PLS-00306: wrong number or types of arguments in call to 'EXPORT_APPLICATION_TO_CLOB'
ORA-06550: line 2, column 5:
PL/SQL: Statement ignored

	at oracle.jdbc.dbaccess.DBError.throwSqlException(DBError.java:189)
	at oracle.jdbc.ttc7.TTIoer.processError(TTIoer.java:242)
	at oracle.jdbc.ttc7.Oall7.receive(Oall7.java:554)
	at oracle.jdbc.ttc7.TTC7Protocol.doOall7(TTC7Protocol.java:1478)
	at oracle.jdbc.ttc7.TTC7Protocol.parseExecuteFetch(TTC7Protocol.java:888)
	at oracle.jdbc.driver.OracleStatement.executeNonQuery(OracleStatement.java:2076)
	at oracle.jdbc.driver.OracleStatement.doExecuteOther(OracleStatement.java:1986)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:2697)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:457)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:531)
	at oracle.apex.APEXExport.ExportFile(APEXExport.java:348)
	at oracle.apex.APEXExport.ExportFiles(APEXExport.java:109)
	at oracle.apex.APEXExport.main(APEXExport.java:865)
Exporting Workspace 1280402716200740:'MET' 
  Completed at Mon May 08 16:02:50 BST 2017

SQL*Plus: Release 11.2.0.4.0 Production on Mon May 8 16:02:50 2017

Copyright (c) 1982, 2013, Oracle.  All rights reserved.

Connected to:
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
With the Partitioning, Oracle Label Security, OLAP, Data Mining,
Oracle Database Vault and Real Application Testing options

Disconnected from Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
With the Partitioning, Oracle Label Security, OLAP, Data Mining,
Oracle Database Vault and Real Application Testing options

Any suggestions?

regards
Daniel

**Comment by martindsouza** [comment]
@zooiduk I'm no longer supporting these scripts as [SQLcl](http://www.oracle.com/technetwork/developer-tools/sqlcl/overview/index.html) has built in functionality that handles the export in one simple command. [This post](https://www.insum.ca/oracle-apex-deployments-youre-doing-it-wrong/) covers how to use SQLcl and its `apex export` command.
